const { describe, it, expect } = require('@jest/globals');
import {
  deriveRequestNameFromUrl,
  deriveTransientRequestNameFromUrl,
  isAutoGeneratedRequestName,
  mergeHeaders,
  transformRequestToSaveToFilesystem
} from './index';

describe('mergeHeaders', () => {
  it('should include headers from collection, folder and request (with correct precedence)', () => {
    const collection = {
      root: {
        request: {
          headers: [
            { name: 'X-Collection', value: 'c', enabled: true }
          ]
        }
      }
    };

    const folder = {
      type: 'folder',
      root: {
        request: {
          headers: [
            { name: 'X-Folder', value: 'f', enabled: true }
          ]
        }
      }
    };

    const request = {
      headers: [
        { name: 'X-Request', value: 'r', enabled: true }
      ]
    };

    const headers = mergeHeaders(collection, request, [folder]);
    const names = headers.map((h) => h.name);
    expect(names).toEqual(expect.arrayContaining(['X-Collection', 'X-Folder', 'X-Request']));
  });
});

describe('transformRequestToSaveToFilesystem', () => {
  it('preserves header and param annotations', () => {
    const item = {
      uid: 'requestuid123456789012',
      type: 'http-request',
      name: 'Annotated Request',
      seq: 1,
      settings: {},
      tags: [],
      examples: [],
      request: {
        method: 'GET',
        url: 'https://example.com',
        params: [
          {
            uid: 'paramuid1234567890123',
            name: 'q',
            value: '1',
            description: '',
            annotations: [{ name: 'param-note', value: 'keep me' }],
            type: 'query',
            enabled: true
          }
        ],
        headers: [
          {
            uid: 'headeruid123456789012',
            name: 'X-Test',
            value: '1',
            description: '',
            annotations: [{ name: 'header-note', value: 'keep me' }],
            enabled: true
          }
        ],
        auth: { mode: 'none' },
        body: { mode: 'none' },
        script: { req: '', res: '' },
        vars: { req: [], res: [] },
        assertions: [],
        tests: '',
        docs: ''
      }
    };

    const transformed = transformRequestToSaveToFilesystem(item);

    expect(transformed.request.params[0].annotations).toEqual([{ name: 'param-note', value: 'keep me' }]);
    expect(transformed.request.headers[0].annotations).toEqual([{ name: 'header-note', value: 'keep me' }]);
  });
});

describe('deriveRequestNameFromUrl', () => {
  it('uses localhost and the last two meaningful path segments', () => {
    expect(deriveRequestNameFromUrl('http://localhost:8090/oauth2/token')).toBe('localhost oauth2 token');
  });

  it('handles localhost URLs without an explicit scheme', () => {
    expect(deriveRequestNameFromUrl('localhost:8090/oauth2/token')).toBe('localhost oauth2 token');
  });

  it('uses a meaningful domain label and skips generic URL parts', () => {
    expect(deriveRequestNameFromUrl('https://api.tamin.ir/api/v1/users/123')).toBe('tamin users');
  });

  it('uses the domain label and drops query strings', () => {
    expect(deriveRequestNameFromUrl('https://esb.yazd.ir/v1/sanareport?NoticedocId=15')).toBe('yazd sanareport');
  });

  it('skips IP hostnames when path context is useful', () => {
    expect(deriveRequestNameFromUrl('https://10.0.227.50:8093/SayahEstelam/EstelamCustomerService.svc?wsdl')).toBe(
      'SayahEstelam EstelamCustomerService'
    );
  });

  it('falls back to hostname when no path exists', () => {
    expect(deriveRequestNameFromUrl('https://example.com/')).toBe('example.com');
  });

  it('does not derive names from template URLs', () => {
    expect(deriveRequestNameFromUrl('{{baseUrl}}/oauth2/token')).toBe('');
  });
});

describe('deriveTransientRequestNameFromUrl', () => {
  it('derives a name only for automatically named requests', () => {
    expect(deriveTransientRequestNameFromUrl('Untitled 1', 'https://api.tamin.ir/oauth2/token')).toBe(
      'tamin oauth2 token'
    );
    expect(deriveTransientRequestNameFromUrl('Login request', 'https://api.tamin.ir/oauth2/token')).toBe('');
  });

  it('recognizes existing automatic request names', () => {
    expect(isAutoGeneratedRequestName('Untitled')).toBe(true);
    expect(isAutoGeneratedRequestName('Untitled 12')).toBe(true);
    expect(isAutoGeneratedRequestName('Untitled12')).toBe(true);
    expect(isAutoGeneratedRequestName('Untitled token')).toBe(false);
  });
});

describe('transformRequestToSaveToFilesystem — forward compatibility', () => {
  // itemToSave is an allow-list, so a field it does not name is deleted from the
  // user's file on the next save. Blocks written by a newer Bruno are exactly
  // the ones we cannot reconstruct, so losing them here is unrecoverable.
  const v4Item = (extra = {}) => ({
    uid: 'abcdefghijklmnopqrstu',
    type: 'http-request',
    name: 'get-user',
    seq: 1,
    request: {
      method: 'GET',
      url: 'https://example.com',
      params: [],
      headers: [],
      body: { mode: 'none' },
      auth: { mode: 'none' },
      script: {},
      vars: {},
      assertions: [],
      tests: '',
      docs: ''
    },
    ...extra
  });

  it('keeps blocks a newer Bruno wrote that we can only store verbatim', () => {
    const unknownBlocks = [
      { name: 'app', raw: 'app {\n  enabled: true\n}' },
      { name: 'auth:akamai-edgegrid', raw: 'auth:akamai-edgegrid {\n  accessToken: tok-123\n}' }
    ];

    const transformed = transformRequestToSaveToFilesystem(v4Item({ unknownBlocks }));

    expect(transformed.unknownBlocks).toEqual(unknownBlocks);
  });

  it('does not invent the field for an ordinary request', () => {
    expect(transformRequestToSaveToFilesystem(v4Item())).not.toHaveProperty('unknownBlocks');
    expect(transformRequestToSaveToFilesystem(v4Item({ unknownBlocks: [] }))).not.toHaveProperty('unknownBlocks');
  });

  it('keeps them when saving a draft', () => {
    const unknownBlocks = [{ name: 'app', raw: 'app {\n  enabled: true\n}' }];
    const item = v4Item({ unknownBlocks });
    item.draft = { ...v4Item({ unknownBlocks }), name: 'edited' };

    const transformed = transformRequestToSaveToFilesystem(item);

    expect(transformed.name).toBe('edited');
    expect(transformed.unknownBlocks).toEqual(unknownBlocks);
  });
});
