name: Gridman CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gridman/develop
      - workspace-git-sync
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-web:
    name: Build web app
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node dependencies
        uses: ./.github/actions/common/setup-node-deps

      - name: Build web app
        run: npm run build:web
